version: '3.8'

services:
    nginx:
        restart: always
        image: openresty/openresty:alpine
#        image: openresty/openresty:1.19.3.1-0-alpine-fat
        container_name: ${APP_NAME}-nginx_lua
        ports:
            - "8055:80"
        volumes:
            - ./project:/project
            - ./docker/embed/nginx/conf.d/default.conf:/usr/local/openresty/nginx/conf/nginx.conf
            - ./lua:/usr/local/openresty/nginx/lua
        depends_on:
            - php-fpm
            - php-cli
        networks:
            - slim-catalog

    php-fpm:
        container_name: ${APP_NAME}-php-fpm
        build:
            context: docker
            dockerfile: development/php-fpm/Dockerfile
        ports:
            - "9001:9000"
        volumes:
            - ./project:/project
        networks:
            - slim-catalog

    php-cli:
        container_name: ${APP_NAME}-php-cli
        build:
            context: docker
            dockerfile: development/php-cli/Dockerfile
        restart: always
        volumes:
            - ./project:/project
        networks:
            - slim-catalog

    maria-db:
        restart: always
        image: mariadb:11.1.3
        container_name: ${APP_NAME}-db
        volumes:
            - ./volumes/database/mysql://var/lib/mysql
        ports:
            - "3355:3306"
        command: [ '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci' ]
        environment:
            - MYSQL_PASSWORD=${DATABASE_PASSWORD}
            - MYSQL_USER=${DATABASE_USER}
            - MYSQL_DATABASE=${DATABASE_NAME}
            - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
        networks:
            - slim-catalog

networks:
    slim-catalog:
        external: true

